<?php
	// STEP 1 : 
	/*
	 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
	 * on the integrations page. For security reasons, these keys are best stored
	 * outside of the webroot in a production implementation.
	 */
	define('IKEY', "iiiiiiiiiiiiiiiiiiiii");
	define('SKEY', "sssssssssssssssssssssss");
	define('HOST', "hhhhhhhhhhhhhhhhhhhhhhhh");
	/*
	 * AKEY : This is something uniquely generated by you for your application
	 * and is not shared with Duo.
	 */	
	define('AKEY', "aaaaaaaaaaaaaaaaaaaaaaaa");
	
	// load here Wep.php
	require_once './src/Web.php';	
	// STEP 1 END 
	
	/*
	 * STEP 3:
	 * Once secondary auth has completed you may log in the user
	 * When this script runs for the first time, secondary authentication hasn't occured yet. Then $_POST['sig_response'] is equal to NULL and we go directly to // check login
	 * When secondary authentication has already occured this script calls itself and then $_POST['sig_response'] is set,  the script goes into the STEP 3 loop
	 */
	if (isset($_POST['sig_response'])) 
	{
	  /*
	     * Verify sig response and log in user. Make sure that verifyResponse
	     * returns the username we logged in with. You can then set any
	     * cookies/session data for that username and complete the login process.
	     */
	    $resp = Duo\Web::verifyResponse(IKEY, SKEY, AKEY, $_POST['sig_response']);
		//echo 'Hi, ' . $resp . '<br>';
	    if ($resp === 'patrick') {
	        // Password protected content would go here.        
	        //echo 'Your content here!';
			// here under we jump to the welcome.html page
			header("Location: ./hourra/welcome.html");
			exit();
	    }
	}
	// STEP 3 - END
	
	// Check Login
	$login = '';
	$pass = '';
	if (!empty($_POST['login']) && !empty($_POST['pass'])) 
	{
		$login = trim($_POST['login']);
		$pass = trim($_POST['pass']);	
		/*
		 * STEP 2:
		 * verify username and password
		 * if the user and pass are good, then generate a sig_request and
		 * load up the Duo iframe for secondary authentication
		 */
		if(($login=="patrick")&&($pass=="pssword"))
		{				
			$sig_request = Duo\Web::signRequest(IKEY, SKEY, AKEY, $_POST['login']);
			echo '<form method="POST" id="duo_form">
			<input type="hidden" name="user" value="'.$login.'" />
			</form>
			';
	       echo' <script type="text/javascript" src="./js/Duo-Web-v2.js"></script>
	        <link rel="stylesheet" type="text/css" href="Duo-Frame.css">
	        <div align="center"><iframe  id="duo_iframe"
	            data-host="'.HOST.'"
	            data-sig-request="'.$sig_request.'" width="900" height="600"
	        ></iframe></div>	';
			$authenticated=1;
		}		
		else 
		{
			$authenticated=0;
		}
	}
?>